import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const { searchParams } = new URL(request.url);
    const format = searchParams.get('format') || 'json';

    const persona = await prisma.persona.findUnique({
      where: { id },
      include: {
        responses: {
          orderBy: { createdAt: 'desc' },
          take: 20
        },
        scenarios: {
          orderBy: { createdAt: 'desc' },
          take: 20
        }
      }
    });

    if (!persona) {
      return NextResponse.json(
        { error: 'Persona not found' },
        { status: 404 }
      );
    }

    if (format === 'json') {
      // Return as JSON download
      const filename = `${persona.name.replace(/\s+/g, '_')}_persona.json`;

      return new NextResponse(JSON.stringify(persona, null, 2), {
        headers: {
          'Content-Type': 'application/json',
          'Content-Disposition': `attachment; filename="${filename}"`,
        },
      });
    } else if (format === 'markdown') {
      // Generate markdown style guide
      const voiceProfile = persona.voiceProfile ? JSON.parse(persona.voiceProfile) : {};
      const beliefs = persona.beliefs ? JSON.parse(persona.beliefs) : {};
      const toneProfile = persona.toneProfile ? JSON.parse(persona.toneProfile) : {};
      const behaviors = persona.behaviors ? JSON.parse(persona.behaviors) : {};

      const markdown = `# ${persona.name} - Character Style Guide

${persona.occupation ? `**Occupation:** ${persona.occupation}` : ''}
${persona.age ? `**Age:** ${persona.age}` : ''}

## Overview

${persona.description || 'No description provided'}

## Background

${persona.background || 'No background provided'}

---

## Voice Characteristics

### Speaking Style
${voiceProfile.speakingStyle || 'Not specified'}

### Vocabulary Level
${voiceProfile.vocabularyLevel || 'Not specified'}

### Sentence Structure
${voiceProfile.sentenceStructure || 'Not specified'}

### Catchphrases
${voiceProfile.catchphrases && voiceProfile.catchphrases.length > 0
  ? voiceProfile.catchphrases.map((p: string) => `- "${p}"`).join('\n')
  : 'None specified'}

### Speech Rhythm
${voiceProfile.speechRhythm || 'Not specified'}

---

## Beliefs & Values

### Political Views
${beliefs.political || 'Not specified'}

### Moral Framework
${beliefs.moral || 'Not specified'}

### Core Philosophy
${beliefs.philosophy || 'Not specified'}

### Core Principles
${beliefs.principles && beliefs.principles.length > 0
  ? beliefs.principles.map((p: string) => `- ${p}`).join('\n')
  : 'None specified'}

---

## Tone Profile

### Default Mood
${toneProfile.defaultMood || 'Not specified'}

### Emotional Range
${toneProfile.emotionalRange || 'Not specified'}

### Humor Style
${toneProfile.humorStyle || 'Not specified'}

### Formality Level
${toneProfile.formalityLevel || 'Not specified'}

---

## Behavioral Patterns

### Decision Making
${behaviors.decisionMaking || 'Not specified'}

### Conflict Response
${behaviors.conflictResponse || 'Not specified'}

### Social Preferences
${behaviors.socialPreferences || 'Not specified'}

### Work Ethic
${behaviors.workEthic || 'Not specified'}

### Coping Mechanisms
${behaviors.copingMechanisms || 'Not specified'}

---

## Usage Stats

- **Total Uses:** ${persona.usageCount}
- **Last Used:** ${persona.lastUsed ? new Date(persona.lastUsed).toLocaleDateString() : 'Never'}
- **Created:** ${new Date(persona.createdAt).toLocaleDateString()}

---

*Generated by Persona GPT*
`;

      const filename = `${persona.name.replace(/\s+/g, '_')}_style_guide.md`;

      return new NextResponse(markdown, {
        headers: {
          'Content-Type': 'text/markdown',
          'Content-Disposition': `attachment; filename="${filename}"`,
        },
      });
    }

    return NextResponse.json(
      { error: 'Invalid format' },
      { status: 400 }
    );
  } catch (error) {
    console.error('Error exporting persona:', error);
    return NextResponse.json(
      { error: 'Failed to export persona' },
      { status: 500 }
    );
  }
}
