export const pdfTemplate = (sop: any) => `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: 'Helvetica', 'Arial', sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
    }
    .header {
      border-bottom: 2px solid #1e40af;
      padding-bottom: 20px;
      margin-bottom: 30px;
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
    }
    .title {
      font-size: 28px;
      font-weight: bold;
      color: #111;
      margin: 0;
    }
    .meta {
      font-size: 12px;
      color: #666;
      text-align: right;
    }
    .status-badge {
      display: inline-block;
      padding: 4px 8px;
      border-radius: 4px;
      background: #f3f4f6;
      font-weight: bold;
      text-transform: uppercase;
      font-size: 11px;
    }
    h1 {
      font-size: 24px;
      color: #1e40af;
      margin-top: 30px;
      border-bottom: 1px solid #e5e7eb;
      padding-bottom: 8px;
    }
    h2 {
      font-size: 18px;
      color: #374151;
      margin-top: 20px;
    }
    p {
      margin-bottom: 15px;
    }
    ul, ol {
      margin-bottom: 15px;
      padding-left: 20px;
    }
    li {
      margin-bottom: 8px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }
    th, td {
      border: 1px solid #d1d5db;
      padding: 8px 12px;
      text-align: left;
    }
    th {
      background-color: #f9fafb;
      font-weight: 600;
    }
    .warning {
      background-color: #fffbeb;
      border-left: 4px solid #f59e0b;
      padding: 12px;
      margin: 15px 0;
      color: #92400e;
    }
    .footer {
      margin-top: 50px;
      border-top: 1px solid #e5e7eb;
      padding-top: 20px;
      font-size: 10px;
      color: #9ca3af;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1 class="title">${sop.title}</h1>
      <p style="margin: 5px 0 0; color: #666;">${sop.category || 'Standard Operating Procedure'}</p>
    </div>
    <div class="meta">
      <div>Version: ${sop.version}</div>
      <div>Updated: ${new Date(sop.updatedAt).toLocaleDateString()}</div>
      <div style="margin-top: 5px;"><span class="status-badge">${sop.status}</span></div>
    </div>
  </div>

  <div class="content">
    ${generateHTMLContent(JSON.parse(sop.content))}
  </div>

  <div class="footer">
    Generated by SOP Generator • ${new Date().toLocaleString()}
  </div>
</body>
</html>
`;

function generateHTMLContent(doc: any) {
    if (!doc || !doc.content) return '';

    return doc.content.map((node: any) => {
        switch (node.type) {
            case 'heading':
                return `<h${node.attrs.level}>${getText(node)}</h${node.attrs.level}>`;
            case 'paragraph':
                const text = getText(node);
                // Check for warning styling from our custom class
                if (node.attrs && node.attrs.class && node.attrs.class.includes('text-red-600')) {
                    return `<div class="warning"><strong>WARNING:</strong> ${text.replace('WARNING:', '')}</div>`;
                }
                return `<p>${text}</p>`;
            case 'bulletList':
                return `<ul>${node.content.map((item: any) => `<li>${generateHTMLContent(item)}</li>`).join('')}</ul>`;
            case 'orderedList':
                return `<ol>${node.content.map((item: any) => `<li>${generateHTMLContent(item)}</li>`).join('')}</ol>`;
            case 'listItem':
                return generateHTMLContent(node); // List items contain paragraphs usually
            case 'table':
                return `<table>
          ${node.content.map((row: any) => `
            <tr>${row.content.map((cell: any) => `
              <${cell.type === 'tableHeader' ? 'th' : 'td'}>${generateHTMLContent(cell)}</${cell.type === 'tableHeader' ? 'th' : 'td'}>
            `).join('')}</tr>
          `).join('')}
        </table>`;
            default:
                return '';
        }
    }).join('');
}

function getText(node: any): string {
    if (node.text) return node.text;
    if (node.content) return node.content.map(getText).join('');
    return '';
}
